[tools]
opentofu = "1.12.5"

[settings]
lockfile = true

[tasks."tofu:plan"]
description = "Run tofu plan"
run = """
export OP_ACCOUNT='zhokhov.1password.com'
export OP_SESSION_zhokhov="$(op signin --raw)"
export GITHUB_TOKEN="$(op read 'op://tailrocks/GitHub/tokens/tofu')"
exec tofu plan "$@"
"""

[tasks."tofu:apply"]
description = "Run tofu apply"
run = """
export OP_ACCOUNT='zhokhov.1password.com'
export OP_SESSION_zhokhov="$(op signin --raw)"
export GITHUB_TOKEN="$(op read 'op://tailrocks/GitHub/tokens/tofu')"
exec tofu apply "$@"
"""
